### ISSUE TITLE
文件缺失以及代码错误

### ISSUE THREAD

**Issue by Delete12137** [yuanpengtu/SANM#3]
你好，非常感谢你们的卓越工作！
我在复现SANM(C2D)时发现你们没有提供c2d的预训练模型，即ckpt_{}_{}.pth。
此外，我复现SANM(DivideMix)时，用下面函数创造的模型结构缺少Decoder。
![image](https://github.com/yuanpengtu/SANM/assets/105090442/1354a6bd-3197-496f-a6e2-aad2e5983ae2)

为此，我修改了下面的函数以跑通代码：
![image](https://github.com/yuanpengtu/SANM/assets/105090442/8b498d6d-0074-43c9-9c79-fed0701a1500)
也就是不使用c2d的预训练模型，就相当于SANM(DivideMix)。但是实验结果却很奇怪，如下图：
![image](https://github.com/yuanpengtu/SANM/assets/105090442/64604777-ce45-468f-a95c-1d833872ac0c)
他直接崩掉了。

请问你可以提供c2d的预训练模型吗，以及是否可以更新一下代码，补充Decoder使得我能够复现SANM(DivideMix)
非常感谢！

**Comment by yuanpengtu** [comment]
C2D的自监督权重可以在这里下载： https://drive.google.com/drive/folders/1qYVdggtNFQZBZ-OqVJm80LBKUKpdLPUm

**Comment by yuanpengtu** [comment]
SANM(DivideMix)的性能在去除decoder情况下在cifar数据集上差别不大，可以尝试不用decoder，用dividemix给的resnet18结构在训练一遍试试

**Comment by steveli88** [comment]
你好，SANM(C2D)移除预训练后，我也得到了类似的实验结果。
![image](https://github.com/yuanpengtu/SANM/assets/85588843/ea3c3cab-181c-444c-bc66-818326e568c6)
请问预训练的影响大吗？

另外，我看到code和文中的公式可能有些区别。
比如，Equation(2)，实际code会比公式复杂些
https://github.com/yuanpengtu/SANM/blob/e929a295ef95335f341e9038b3c2eec2e7805292/Train_cifar.py#L58-L65
Equation(4)， 实际code好像没有以最高activation的点作为中心产生mask
https://github.com/yuanpengtu/SANM/blob/e929a295ef95335f341e9038b3c2eec2e7805292/Train_cifar.py#L67-L81

请问这种区别会影响到performance吗？需要以paper为准还是按照code为准？
非常感谢！

**Comment by yuanpengtu** [comment]
抱歉，已修正，Train_cifar.py里attention_erase_map函数59行存在一个bug，导致Lu损失值异常，SANM(DivideMix)现在应该正常了，可以再试试

**Comment by yuanpengtu** [comment]
SANM(DivideMix)可以用当前模型，不load权重

**Comment by yuanpengtu** [comment]
> 你好，SANM(C2D)移除预训练后，我也得到了类似的实验结果。 ![image](https://private-user-images.githubusercontent.com/85588843/296291040-ea3c3cab-181c-444c-bc66-818326e568c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMzI5ODQsIm5iZiI6MTcwNTEzMjY4NCwicGF0aCI6Ii84NTU4ODg0My8yOTYyOTEwNDAtZWEzYzNjYWItMTgxYy00NDRjLWJjNjYtODE4MzI2ZTU2OGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA3NTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MGRlMWE0ZjI0MTVjNzAxMjIzZjExMGI2MTUzZDRmOTRmODE2NmFkMTRhODE3N2E3NGVlYjdjNmY1YjExOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oh-knNYvWMPjsYP5kMozE3nCc5Ezv1kSNEQIdNszbxY) 请问预训练的影响大吗？
> 
> 另外，我看到code和文中的公式可能有些区别。 比如，Equation(2)，实际code会比公式复杂些
> 
> https://github.com/yuanpengtu/SANM/blob/e929a295ef95335f341e9038b3c2eec2e7805292/Train_cifar.py#L58-L65
> 
> 
> Equation(4)， 实际code好像没有以最高activation的点作为中心产生mask
> https://github.com/yuanpengtu/SANM/blob/e929a295ef95335f341e9038b3c2eec2e7805292/Train_cifar.py#L67-L81
> 
> 请问这种区别会影响到performance吗？需要以paper为准还是按照code为准？ 非常感谢！

下面这个区别对性能影响不大，可以以code为准，Eq.2对应59后半部分，为了增强样本多样性，新增了均匀采样的扰动项

**Comment by Delete12137** [comment]
![image](https://github.com/yuanpengtu/SANM/assets/105090442/017feb4e-72ac-45bc-a9f1-71b71897cae1)
还是不太对，更新完代码之后在warmup阶段就会出问题了
我就是直接把SANM(C2D)的预训练权重load部分代码给注释掉了

不跑高噪音率，直接运行你的代码中默认的cifar10-sym-0.5也有些问题，如下图：
![image](https://github.com/yuanpengtu/SANM/assets/105090442/217e2911-e2b1-4127-9bb2-4aa9efbb33e6)
![image](https://github.com/yuanpengtu/SANM/assets/105090442/3f0c158c-0703-41f3-89e4-4c0082fc59c3)
上面的图是你代码的运行结果，下面的图是我复现DivideMix的结果。可以看到warmup阶段两者性能差异就很大，但是你的warmup代码和DIvedeMix是一样的，我不知道是哪里出了问题。非常感谢你的解答！

**Comment by yuanpengtu** [comment]
这个问题C2D原文其实也有，他用的SupCEResNet在没有load自监督权重的情况下的结果比用dividemix的resnet18的结构会更差，我更新了PreResNet.py和Train_cifar.py（增加了DivideMix原文的resnet18结构），可以再试试

**Comment by Delete12137** [comment]
warmup阶段的训练性能有所改善，但还是达不到DivideMix的warmup阶段性能。
![image](https://github.com/yuanpengtu/SANM/assets/105090442/b73358a1-8fca-4fce-b738-1cbd50ed803a)
将更新后的Train_cifar.py中的DivideMix改为True就可以直接运行SANM(DivideMix).结果如下：
![image](https://github.com/yuanpengtu/SANM/assets/105090442/75f041f1-8101-4c99-8f4d-ca6a56fba723)
可以看到在warmup阶段仍与DivideMix有较大差距，不过在warmup结束后的几轮训练中，性能快速提升，减小和DMix的差距。
我看了warmup阶段的代码，和DMix是一样的，我很好奇为什么warmup阶段的性能差异会这么大，毕竟模型结构一致，训练的数据和策略也一致。不应该有这么大的差异。

**Comment by Delete12137** [comment]
而且我分别跑了0.5和0.9噪音率下的实验。
0.5噪音率下的实验最终可以达到论文汇报的结果，但是0.9下的实验在训练中突然崩溃为随机预测了，如下图实验结果：
![image](https://github.com/yuanpengtu/SANM/assets/105090442/b2e6ce93-7566-492c-be93-e6b7a91958cd)

**Comment by yuanpengtu** [comment]
换到0.9噪声，需要调整unlabel loss的权重，不是默认的那个，这个需要自己调一下，你试试dividemix0.9噪声用默认参数，应该也会很差

**Comment by Delete12137** [comment]
我调整参数了，DMix我复现了他的所有结果。SANM的参数我也是使用的一样的参数，对应不同噪音率的lamada_u我也有修改。下图是脚本命令行。
![image](https://github.com/yuanpengtu/SANM/assets/105090442/8f7e8c23-a821-4d2d-a50a-11724133fd57)
![image](https://github.com/yuanpengtu/SANM/assets/105090442/d8469e34-55b1-4eee-b47f-1bb8b62c478a)

**Comment by yuanpengtu** [comment]
因为SANM（DivideMIx）相比于原版的DivideMIx数据量大了几倍，所以这个lambda_u和dividemix不一样

**Comment by Delete12137** [comment]
能够麻烦您提供不同噪音率下的lambda_u值吗，我跑一次实验需要两天，调参成本太高了，不胜感激。

**Comment by yuanpengtu** [comment]
抱歉，这个我也忘了每个setting要设置的值了，这个是22年6月左右在公司实习的时候做的，去年3月走的时候忘了把所有的log也下下来了，只记得噪声越大，lambda_u越大.......

**Comment by yuanpengtu** [comment]
如果是C2D版本的SANM，应该对这个lambda_u设置相对不那么敏感

**Comment by Delete12137** [comment]
好的麻烦了

**Comment by wangnaihao** [comment]
其实在dataloder做归一化的时候权重有一个一直是cifar100的 不知道是不是这个原因（我猜大概率是

**Comment by yuanpengtu** [comment]
> 其实在dataloder做归一化的时候权重有一个一直是cifar100的 不知道是不是这个原因（我猜大概率是

感谢，Check了一下，这个地方确实有点问题，已修正
