### ISSUE TITLE
the code has some issues that can not be runned

### ISSUE THREAD

**Issue by LanXiaoPang613** [yuanpengtu/SANM#5]
There are some issues in the released code, where the function of create_model is error.
def create_model(dataset='cifar10', num_classes=10):
    model = create_model_selfsup(dataset = dataset, num_classes = num_classes)
    model = model.cuda()
    return model
The pretrained model has not been provided: torch.load('./pretrained/ckpt_{}_{}.pth'.format(dataset, net))

**Comment by yuanpengtu** [comment]
For the pre-trained model weights, please refer to C2D (https://github.com/ContrastToDivide/C2D). The weights can be downloaded in "https://drive.google.com/drive/folders/1qYVdggtNFQZBZ-OqVJm80LBKUKpdLPUm"

**Comment by LanXiaoPang613** [comment]
![image](https://github.com/yuanpengtu/SANM/assets/35187545/82b5126b-dbe8-4533-9e31-de7e55fcddd1)
Thank for your reply.  I adopt c2d+sanm to train on cifa10 with 50%-sym noise, and the hyperparameter Settings are consistent with the paper. The result is shown in the above figure, with a best result of 95.6%, much lower than the 96.4% in the manuscript. Can you check what's wrong with the configuration for me. The following is the parameter configuration:
![image](https://github.com/yuanpengtu/SANM/assets/35187545/a1447cdd-b707-4590-b340-df712a1e9666)
![image](https://github.com/yuanpengtu/SANM/assets/35187545/7fae6902-fec3-4a26-9d41-1278e1cdaaf4)

**Comment by yuanpengtu** [comment]
For c2d+sanm, you may need to set the weight of unlabeled data to a lower value to achieve better performance.

**Comment by luxiaobai030** [comment]
你好我想问一下这个unlabeled data的权重设置为多少能达到最好的效果？
