### ISSUE TITLE
强增强

### ISSUE THREAD

**Issue by wangnaihao** [yuanpengtu/SANM#6]
您好！我注意到dividemix是没有强增强的，如果单独引入强增强效果提升也会很明显，请问当时有做过只用强增强和用您提出的方法的对比吗

**Comment by yuanpengtu** [comment]
我记得强增强单独引入的话，低噪情况会有提升，但是高噪会掉点，因为他的prediction结果会让伪标签质量变差

**Comment by wangnaihao** [comment]
我的意思是说将其中一支弱增强换成强增强，另外我注意到，您的工作其实引入了6个强增强，所以在消融时是强增强全部去掉吗，还是仅去掉通过erase的增强图像

**Comment by yuanpengtu** [comment]
消融的时候是都去掉了的，如歌把弱增强换成强增强的话会掉点，猜测可能是因为全是强增强的到的伪标签不靠谱，扰动太大了

**Comment by wangnaihao** [comment]
感谢您的回答，那这样不会导致模块的收益可能是由于一些强增强的引入导致的嘛？因为6个强增强其实并没有都应用您所提出的关键方法

**Comment by yuanpengtu** [comment]
6个强增强里面只有两个是没有erase的，这两个的收益在高噪声情况下比较低

**Comment by wangnaihao** [comment]
谢谢您的回复，但是看到您开源的这个版本只用了一支强增强
```inputs_erase = torch.cat([inputs_x, inputs_u], dim=0)```

**Comment by yuanpengtu** [comment]
这个会返回erase最小激活和最大激活的data，所以只有两个strong aug是没加erase的
